version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i -g @angular/cli
      - npm i -g typescript
      - echo "install nodejs"
  pre_build:
    commands:
      ## Install NPM dependencies in both the Angular
      - npm install ##Express app source folder name
  build:
    commands:
      ## angular.josn outputPath is set to ../dist/public which is the Express apps static files folder.
      - ng build
      - echo "build complete"
artifacts:
  files:
  ##this will take all files within the dist folder which will then be zipped by CodeBuild then stored in S3
    - "**/*"
  base-directory: "dist/app-museums-angular-aws"
