version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm install -g typescript
      - echo "install nodejs"
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build
artifacts:
  files:
      - '**/*'
  discard-paths: no
  base-directory: dist/app-museums-angular-aws
