version: 0.2
env:
  variables:
    APP_NAME: "app-museums-angular-aws"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/$APP_NAME
